routes:
  /: home

collections:
  /blog/:
    permalink: /blog/{slug}/
    template: index
  /test/:
    permalink: /test/{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
